name: Check with prettier
on: push
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run prettier
        run: npx -p prettier@1.19 prettier --check "**/*.{ts,js}"
